services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: incident
      POSTGRES_PASSWORD: incident
      POSTGRES_DB: incident
    ports:
      - "5499:5432"
    volumes:
      - incident-data:/var/lib/postgresql

volumes:
  incident-data:
